- name: Check if node is installed
  stat:
    path: '/etc/kubernetes/kubelet.conf'
  register: kubeletconf

- name: Join node to Cluster
  when: not kubeletconf.stat.exists
  block:
  - name: Get Join Command
    delegate_to: "{{ groups['controlplane'][0] }}"
    command:
      cmd: kubeadm token create --print-join-command
    register: token_output

  - name: Join Cluster
    shell:
      cmd: "{{ token_output.stdout_lines[-1] }}"
