- name: Check if node is installed
  stat:
    path: '/etc/kubernetes/admin.conf'
  register: adminconf

- name: Join node to Cluster
  when: not adminconf.stat.exists
  block:
  - name: Get Certificate Key
    delegate_to: "{{ groups['controlplane'][0] }}"
    command:
      cmd: kubeadm init phase upload-certs --upload-certs
    register: certs_output

  - name: Get Join Command
    delegate_to: "{{ groups['controlplane'][0] }}"
    command:
      cmd: kubeadm token create --print-join-command
    register: token_output

  - name: Join Cluster
    shell:
      cmd: "{{ token_output.stdout_lines[-1] }} --control-plane --certificate-key {{ certs_output.stdout_lines[-1] }}"
