- name: Setup wifi
  when: wifi is defined
  block:
    - name: Add wpasupplicant
      ansible.builtin.apt:
        name: wpasupplicant
        state: present

    - name: Stop default
      ansible.builtin.systemd_service:
        name: wpa_supplicant
        state: stopped
        enabled: false

    - name: Template wifi service
      template:
        dest: /etc/systemd/system/ongy-wifi.service
        mode: 0644
        src: ongy-wifi.service

    - name: Start ongy
      ansible.builtin.systemd_service:
        daemon_reload: true
        name: ongy-wifi
        state: started
        enabled: true

- name: Remove wpasupplicant
  when: not (wifi is defined)
  ansible.builtin.apt:
    name: wpasupplicant
    state: absent
    purge: true

